#!/usr/bin/python

import cgi_bin

# print header
print('<title>Doc. Produced by CGI</title>')

form = cgi_bin.FieldStorage()

print "<h2> Method incr </h2>"
print "<p>Ok, new value = {0} </p>".format(int(form["val"]) + 1)
