#!/usr/bin/python
import sys

import cgi_bin
import inflect

import xml.etree.ElementTree as ET

form = cgi_bin.FieldStorage()

p = inflect.engine()
new_value = int(form["incrementNum"]) + 1

root = ET.Element("string")
head = ET.SubElement(root, "value")

head.text = str(new_value)

# wrap it in an ElementTree instance, and save as XML
tree = ET.ElementTree(root)

print('<?xml version="1.0" encoding="utf-8" ?>')
tree.write(sys.stdout)