#!/usr/bin/python
import sys

import cgi_bin
import inflect

import xml.etree.ElementTree as ET

form = cgi_bin.FieldStorage()

p = inflect.engine()
string_convert = p.number_to_words(int(form["ubiNum"]))

root = ET.Element("string")
head = ET.SubElement(root, "value")

head.text = string_convert

# wrap it in an ElementTree instance, and save as XML
tree = ET.ElementTree(root)

print('<?xml version="1.0" encoding="utf-8" ?>')
tree.write(sys.stdout)