#!/usr/bin/python

import os

# print header
print('<title>Doc. Produced by CGI</title>')

query_string = os.environ["QUERY_STRING"]
print "<h2> Welcome </h2>"

key, value = os.environ["QUERY_STRING"].split('=')

print "<p>Hi, " + value + " </p>"
